### ISSUE TITLE
Boox Note Air - works!

### ISSUE THREAD

**Issue by marbetschar** [leath-dub/vboox#3]
Just stopped by and wanted to say thank you for the work you put into this! :heart: 

I can confirm that it also works for the original Note Air device - not only for Note Air 2:
I installed the current state of vboox on my Linux machine (ArchLinux, GNOME, Wayland), compiled and ran it. After I selected Note Air 2 device, I'm able to remote control the mouse using the Note Air as external tablet - very neat!

So again, thank you very much! Any plans in (potential) deeper system integration such as a systemd service or so?

**Comment by leath-dub** [comment]
> Just stopped by and wanted to say thank you for the work you put into this! ❤️
> 
> I can confirm that it also works for the original Note Air device - not only for Note Air 2: I installed the current state of vboox on my Linux machine (ArchLinux, GNOME, Wayland), compiled and ran it. After I selected Note Air 2 device, I'm able to remote control the mouse using the Note Air as external tablet - very neat!
> 
> So again, thank you very much! Any plans in (potential) deeper system integration such as a systemd service or so?

I don't actually use systemd (openrc) and the way I do it on my system is just in my xprofile: overall it is a bit hacky as I have left it right now, because after you set it up it just works.

There is a "daemon" script on the repo "vbooxd.sh" and you can set it to run in the background with:

```sh
setsid -f sh -c "exec ./vbooxd.sh $1 2>&1 > /dev/null"
```

This script is not tested outside of my own machines however it should poll over an interval of 10 seconds to see if there is a device and try to launch vboox in the backround.

Also feel free to contribute or fork, though if you fork and make something nice id love to here about it !

**Comment by leath-dub** [comment]
> Just stopped by and wanted to say thank you for the work you put into this! ❤️
> 
> I can confirm that it also works for the original Note Air device - not only for Note Air 2: I installed the current state of vboox on my Linux machine (ArchLinux, GNOME, Wayland), compiled and ran it. After I selected Note Air 2 device, I'm able to remote control the mouse using the Note Air as external tablet - very neat!
> 
> So again, thank you very much! Any plans in (potential) deeper system integration such as a systemd service or so?

Also thanks for testing it out ! I am not surprised that it worked despite setting NoteAir2 as the device: I think most of the devices use the exact same digitizer however I could not make this assumption while developing as I did not find any specs for the devices (I emailed boox directly about it to no avail also).
